name: Build and deploy
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '**.py'
      - 'index.yml'
      - 'pyproject.toml'
      - 'poetry.lock'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '**.py'
      - 'index.yml'
      - 'pyproject.toml'
      - 'poetry.lock'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"
        cache-dependency-path: poetry.lock

    - name: Install library
      run: poetry install --no-interaction

    - name: Build html files
      env:
        INDEX: index.yml
        TEMPLATES: templates
        OUTPUT: build
      run: |
        poetry run python -m pypi_index_builder.build
        touch build/.nojekyll

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        git-config-name: github-actions[bot]
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
        folder: build
        single-commit: true
      if: github.event_name != 'pull_request'
