name: Build and deploy
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '**.py'
      - 'index.yml'
      - 'pyproject.toml'
      - 'uv.lock'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '**.py'
      - 'index.yml'
      - 'pyproject.toml'
      - 'uv.lock'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v6.8.0
      with:
        version: latest

    - name: Build html files
      env:
        INDEX: index.yml
        TEMPLATES: templates
        OUTPUT: build
      run: |
        uv run python -m pypi_index_builder.build
        touch build/.nojekyll

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        git-config-name: github-actions[bot]
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
        folder: build
        single-commit: true
      if: github.event_name != 'pull_request'
